# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgementExperienceInfos', models.TextField(default=None, verbose_name='法院观点|')),
                ('judgementDate', models.DateField(default=datetime.date(2017, 8, 19), verbose_name='裁决日期')),
                ('previousArea', models.IntegerField(default=None, verbose_name='严重等级')),
                ('caseType', models.CharField(default=None, max_length=256, verbose_name='案件类型')),
                ('judgementType', models.CharField(default=None, max_length=256, verbose_name='文书性质')),
                ('case_id', models.CharField(default=None, max_length=256, verbose_name='案件ID')),
                ('trialRound', models.IntegerField(default=0, verbose_name='几审')),
                ('caseNumber', models.CharField(default=None, max_length=111, verbose_name='案号')),
                ('title', models.CharField(default=None, max_length=256, verbose_name='标题')),
                ('publishDate', models.DateField(default=datetime.date(2017, 8, 19), verbose_name='出版日期')),
                ('sourceName', models.CharField(default='', max_length=256, verbose_name='来源名称')),
                ('sourceUrl', models.CharField(default='', max_length=256, verbose_name='来源URL')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=121, verbose_name='关键词')),
            ],
        ),
        migrations.CreateModel(
            name='LawFirmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawFirm', models.CharField(max_length=123, verbose_name='事务所')),
                ('isClaimed', models.BooleanField(verbose_name=False)),
                ('originalLawFirm', models.CharField(max_length=123, verbose_name='事务所2')),
                ('name', models.CharField(max_length=123, verbose_name='名字')),
                ('originalLawyerName', models.CharField(max_length=223, verbose_name=';;;')),
            ],
        ),
        migrations.CreateModel(
            name='LawTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222, verbose_name='机构或个人案例事名称')),
                ('law_type', models.CharField(max_length=222, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalOpponentLawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawFirmInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oollfi', to='itslaw.LawTypes', verbose_name='被告代理事务所信息')),
                ('layerInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oolli', to='itslaw.LawTypes', verbose_name='被告代理律师信息')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='代表数值')),
                ('text', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='SubParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typetext', models.CharField(default='待填充H1', max_length=111, verbose_name='H1')),
                ('typenum', models.IntegerField(default=0, verbose_name='type数')),
                ('paragraphs', models.ManyToManyField(to='itslaw.Paragraphs', verbose_name='段落')),
            ],
        ),
        migrations.AddField(
            model_name='casedetail',
            name='court',
            field=models.ManyToManyField(default=None, related_name='court', to='itslaw.LawTypes', verbose_name='审理法院'),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='judges',
            field=models.ManyToManyField(default=None, related_name='judge', to='itslaw.LawTypes', verbose_name='合议庭'),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='keywords',
            field=models.ManyToManyField(default=None, to='itslaw.Keywords', verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='opponentLawyers',
            field=models.ManyToManyField(default=None, to='itslaw.LawFirmInfo', verbose_name='被告代理律师'),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='opponents',
            field=models.ManyToManyField(default=None, related_name='opponent', to='itslaw.LawTypes', verbose_name='被告'),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='originalOpponentLawyer',
            field=models.ManyToManyField(default=None, related_name='ool', to='itslaw.OriginalOpponentLawyer', verbose_name='原告代理律师'),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='paragraphs',
            field=models.ManyToManyField(default=None, to='itslaw.SubParagraph', verbose_name='内容段落条目'),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='proponents',
            field=models.ManyToManyField(default=None, related_name='proponent', to='itslaw.LawTypes', verbose_name='上诉人|原告'),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='reason',
            field=models.ManyToManyField(default=None, related_name='reason', to='itslaw.LawTypes', verbose_name='案由'),
        ),
    ]
