# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itslaw', '0002_auto_20170819_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetail',
            name='reason',
        ),
        migrations.AddField(
            model_name='casedetail',
            name='reason',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reason', to='itslaw.LawTypes', verbose_name='案由'),
        ),
    ]
