# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itslaw', '0003_auto_20170819_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subparagraph',
            name='typenum',
            field=models.CharField(default='0', max_length=50, verbose_name='type数'),
        ),
    ]
