# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itslaw', '0004_auto_20170819_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subparagraph',
            name='typenum',
            field=models.IntegerField(default=111111, verbose_name='type数'),
        ),
    ]
